name: Building Machine Image
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Building MI for AWS & GCP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      - name: Configure GCP Credentials
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setting GCP SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Setting GCP Access Key
        working-directory: src/infra
        run: |
          echo '${{ secrets.GCP_CREDENTIALS }}' >> .gcp-key.json

      - name: Install Packer 
        uses: hashicorp/setup-packer@main

      - name: Building Artifact
        run: zip -r webapp.zip ./* -x "*.git*"

      - name: Setting .env
        working-directory: src/infra/scripts
        run: |
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env
          echo "DIALECT=${{ secrets.DIALECT }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          cat .env

      - name: Setting .env
        working-directory: src
        run: |
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env
          echo "DIALECT=${{ secrets.DIALECT }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          cat .env

      - name: Packer Initialization
        working-directory: src/infra
        run: packer init .

      - name: Building Image
        working-directory: src/infra
        env:
          AMI_USER: ${{ secrets.AMI_USER }}
        run: packer build .