name: Packer Status Check
on:
  pull_request:
    branches:
      - main

env:
  packer-version: ">=1.10.0"

jobs:
  status-check:
    name: Packer Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Packer 
        uses: hashicorp/setup-packer@main

      - name: Building Artifact
        run: zip -r webapp.zip ./*

      - name: Configure GCP Credentials
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setting GCP SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Setting GCP Access Key
        working-directory: src/infra
        run: | 
          echo '${{ secrets.GCP_CREDENTIALS }}' >> .gcp-key.json

      - name: Debug
        working-directory: src/infra
        run: cat .gcp-key.json

      - name: Viewing Files
        run: |
          pwd
          ls
          ls -ltr
        
      - name: Setting .env
        working-directory: src/infra/scripts
        run: |
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env 
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "AMI_USER=${{ secrets.AMI_USER }}" >> .env
          cat .env

      - name: Packer Initialization
        working-directory: src/infra
        run: packer init .

      - name: Packer Format
        working-directory: src/infra
        run: packer fmt -check .

      - name: Packer Validate
        working-directory: src/infra
        env:
          AMI_USER: ${{ secrets.AMI_USER }}
          DEV_PROJECT_ID: ${{ secrets.DEV_PROJECT_ID }}
          DEMO_PROJECT_ID: ${{ secrets.DEMO_PROJECT_ID }}
        run: packer validate .