name: Packer Status Check
on:
  pull_request:
    branches:
      - main

env:
  packer-version: ">=1.10.0"

jobs:
  status-check:
    name: Packer Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Packer 
        uses: hashicorp/setup-packer@main

      - name: Building Artifact
        run: zip -r webapp.zip ./

      - name: Current Directory
        run: pwd

      - name: Viewing Files
        run: ls -l 
        
      - name: Setting .env
        working-directory: src/infra/scripts
        run: |
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env 
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          cat .env

      - name: Packer Initialization
        working-directory: src/infra
        run: packer init .

      - name: Packer Format
        working-directory: src/infra
        run: packer fmt .

      - name: Packer Validate
        working-directory: src/infra
        run: packer validate .