name: Webapp-Workflow

on:
  pull_request:
    - main

jobs:
  build:
    name: Webapp Setup
    runs-on: ubuntu-latest

    steps:
      - name: Updating Packgaes
        runs: sudo apt update -y
      
      - name: Upgrading Packages
        runs: sudo apt upgrade -y

      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Installing MySQL
        runs: sudo apt install mysql-server

      - name: Starting MySQL
        runs: sudo systemctl start mysql
      
      - name: Configuring DB
        runs: sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY ${{secrets.DATABASE_PASSWORD}};"
        