name: Webapp-Workflow

on:
  pull_request:
    branches:
      - main
    
jobs:
  build:
    name: Webapp Setup
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{DATABASE_PASSWORD}}
          MYSQL_DATABASE: ${{DATABASE_NAME}}
          MYSQL_USER: ${{DATABASE_USERNAME}}
        ports:
          - 3306:3306
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setting up MySQL
        run: sudo apt install mysql-client -y
      
      - name: Status of MySQL
        run: sudo systemctl status mysql