name: Webapp-Workflow

on:
  pull_request:
    branches:
      - main
    
jobs:
  build:
    name: Webapp Setup
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DATABASE_NAME }}
          MYSQL_USER: ${{ secrets.DATABASE_USERNAME }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setting up MySQL client
        run: sudo apt-get install mysql-client -y

      # Wait for MySQL to be ready
      - name: Wait for MySQL to be ready
        run: |
          until mysql -h mysql -u root -p${{ secrets.DATABASE_PASSWORD }} -e "SHOW DATABASES;"; do
            echo "Waiting for MySQL..."
            sleep 5
          done
          echo "MySQL is ready!"

      # Create the database if it doesn't exist
      - name: Creating Database
        run: |
          mysql -h mysql -u root -p${{ secrets.DATABASE_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS CSYE6225;"
