name: WebApp-Workflow

on:
  pull_request: 
    branches:
      - main

jobs:
  build:
    name: WebApp Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          cd src
          npm install
      
      - name: Run Tests
        run: npx jest 